/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MapType = { 'Livik' : null } |
  { 'Sanhok' : null } |
  { 'Miramar' : null } |
  { 'Vikendi' : null } |
  { 'Erangel' : null };
export type Mode = { 'Duo' : null } |
  { 'Squad' : null } |
  { 'Solo' : null };
export interface Registration {
  'id' : bigint,
  'teamName' : [] | [string],
  'playerName' : string,
  'contactNumber' : string,
  'bgmiId' : string,
  'registeredAt' : bigint,
  'tournamentId' : bigint,
}
export interface Tournament {
  'id' : bigint,
  'map' : MapType,
  'status' : TournamentStatus,
  'registeredCount' : bigint,
  'date' : string,
  'mode' : Mode,
  'name' : string,
  'createdAt' : bigint,
  'totalSlots' : bigint,
}
export type TournamentStatus = { 'closed' : null } |
  { 'active' : null } |
  { 'upcoming' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTournament' : ActorMethod<
    [string, string, string, string, bigint, string],
    bigint
  >,
  'deleteRegistration' : ActorMethod<[bigint], undefined>,
  'deleteTournament' : ActorMethod<[bigint], undefined>,
  'getAllRegistrations' : ActorMethod<[], Array<Registration>>,
  'getAllTournaments' : ActorMethod<[], Array<Tournament>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTournament' : ActorMethod<[bigint], Tournament>,
  'getTournamentRegistrations' : ActorMethod<[bigint], Array<Registration>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerForTournament' : ActorMethod<
    [bigint, string, string, [] | [string], string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTournament' : ActorMethod<
    [
      bigint,
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [bigint],
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];