/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Registration = IDL.Record({
  'id' : IDL.Nat,
  'teamName' : IDL.Opt(IDL.Text),
  'playerName' : IDL.Text,
  'contactNumber' : IDL.Text,
  'bgmiId' : IDL.Text,
  'registeredAt' : IDL.Int,
  'tournamentId' : IDL.Nat,
});
export const MapType = IDL.Variant({
  'Livik' : IDL.Null,
  'Sanhok' : IDL.Null,
  'Miramar' : IDL.Null,
  'Vikendi' : IDL.Null,
  'Erangel' : IDL.Null,
});
export const TournamentStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
  'upcoming' : IDL.Null,
});
export const Mode = IDL.Variant({
  'Duo' : IDL.Null,
  'Squad' : IDL.Null,
  'Solo' : IDL.Null,
});
export const Tournament = IDL.Record({
  'id' : IDL.Nat,
  'map' : MapType,
  'status' : TournamentStatus,
  'registeredCount' : IDL.Nat,
  'date' : IDL.Text,
  'mode' : Mode,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'totalSlots' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTournament' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteRegistration' : IDL.Func([IDL.Nat], [], []),
  'deleteTournament' : IDL.Func([IDL.Nat], [], []),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], []),
  'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTournament' : IDL.Func([IDL.Nat], [Tournament], ['query']),
  'getTournamentRegistrations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerForTournament' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTournament' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Registration = IDL.Record({
    'id' : IDL.Nat,
    'teamName' : IDL.Opt(IDL.Text),
    'playerName' : IDL.Text,
    'contactNumber' : IDL.Text,
    'bgmiId' : IDL.Text,
    'registeredAt' : IDL.Int,
    'tournamentId' : IDL.Nat,
  });
  const MapType = IDL.Variant({
    'Livik' : IDL.Null,
    'Sanhok' : IDL.Null,
    'Miramar' : IDL.Null,
    'Vikendi' : IDL.Null,
    'Erangel' : IDL.Null,
  });
  const TournamentStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
    'upcoming' : IDL.Null,
  });
  const Mode = IDL.Variant({
    'Duo' : IDL.Null,
    'Squad' : IDL.Null,
    'Solo' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'id' : IDL.Nat,
    'map' : MapType,
    'status' : TournamentStatus,
    'registeredCount' : IDL.Nat,
    'date' : IDL.Text,
    'mode' : Mode,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'totalSlots' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTournament' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteRegistration' : IDL.Func([IDL.Nat], [], []),
    'deleteTournament' : IDL.Func([IDL.Nat], [], []),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], []),
    'getAllTournaments' : IDL.Func([], [IDL.Vec(Tournament)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTournament' : IDL.Func([IDL.Nat], [Tournament], ['query']),
    'getTournamentRegistrations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerForTournament' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTournament' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };